### ISSUE TITLE
how to calculate the cost of multiple recursion of the same level

### ISSUE THREAD

**Issue by iamake** [pa-bru/graphql-cost-analysis#13] opened 2018-06-28 16:58 UTC
Please advise how to calculate the cost of the below query

      query {
        first(limit: ${limit}) {
          second(limit: ${limit}) {
            int
          }
          anotherSecond(limit: ${limit}) {
            int
          }
        }
      }

Given here the cost map

    type Query {
      first (limit: Int): First @cost(
        multipliers: ["limit"], useMultipliers: true, complexity: ${firstComplexity}
      )
    }

    type First implements BasicInterface {
      string: String
      int: Int
      second (limit: Int): Second @cost(
        multipliers: ["limit"], useMultipliers: true, complexity: ${secondComplexity}
      )
      anotherSecond (limit: Int): Second @cost(
        multipliers: ["limit"], useMultipliers: true, complexity: ${secondComplexity}
      )
    }

    type Second implements BasicInterface {
      int: Int
    }

I believe this below is the correct test case, correct me if I was wrong

    const firstCost = limit * firstComplexity
    const secondCost = limit * limit * secondComplexity
    const anotherSecondCost = limit * limit * secondComplexity

    const result = firstCost + secondCost + anotherSecondCost
    expect(visitor.cost).toEqual(result)

Reference:
https://github.com/iamake/graphql-cost-analysis/commit/2df09dab61f3ec17faebeaa8611f72cc1d250281

**Comment by pa-bru** [comment] 2018-06-29 12:52
Hi @iamake, 

Yes you are right! it seems to be the correct test case but the current `CostAnalysis` code adds systematically the multiplier to the `CostAnalysis.operationMultipliers` list which isn't what we want for the cost computation.

I think we can tranform the `operationMultipliers` array to contain each multiplier value but also the corresponding field.

e.g: 
```
[{value: 10, field: {anotherSecond:
       { type: Second,
         description: '',
         args: [ [Object] ],
         deprecationReason: undefined,
         astNode:
          { kind: 'FieldDefinition',
            description: undefined,
            name: [Object],
            arguments: [Array],
            type: [Object],
            directives: [Array],
            loc: [Object] },
         isDeprecated: false,
         name: 'anotherSecond' }}}]
```

So in `computeNodeCost` we will be able to remove the siblings multipliers that we don't want to use for the cost computation of the current field. 

```
this.operationMultipliers = this.operationMultipliers.filter(
  multiplier => {
    const useless =
      multiplier.field.type === field.type &&
      multiplier.field.name in fields
    return !useless
  }
)
```
we could add it here: https://github.com/pa-bru/graphql-cost-analysis/blob/master/src/costAnalysis.js#L331

What you think about this solution ? feel free to give your opinion and to propose a solution if you have one :)

**Comment by iamake** [comment] 2018-07-02 19:11
I decided to write another version of graphql-cost-analysis here:
https://github.com/iamake/graphql-cost

It's a simplified version of graphql-cost-analysis which solves this problem. And yes, many lines of the code were inspired by you. Thanks !

**Comment by pa-bru** [comment] 2018-07-03 09:19
Ok no problem ! I saw you decided to add a new attribute `childrenMultipliers`. I think it's a good idea to separate parent multipliers from current field multipliers. I will think about that when solving the problem in this repo. But I think it's not a good idea to have to precise the parent multipliers in the directive.

**Comment by pa-bru** [comment] 2018-09-16 13:34
duplicate of #14

**Closed as completed** 2018-09-16 13:35 UTC
Labels: duplicate
